site_name: miguelarbesu/asd-asd
repo_name: miguelarbesu/asd-asd
repo_url: https://github.com/miguelarbesu/asd-asd
theme:
  name: material
  palette:
    primary: blue grey
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - search
  - mkdocstrings
